<?php

?>
<div class="container">
    <div class="row">
        <div class="span12">
            <legend>
                <h3>Email Transport Settings</h3>
            </legend>
            <h5>
                Select preferred transport
            </h5>
            <?php echo $this->form()->openTag($form); ?>
            <dl class="dl-horizontal">
                <?php foreach($form->get('transport')->getValueOptions() as $value => $label): ?>
                <dt>
                    <input 
                        type="radio" 
                        name="transport" 
                        value="<?php echo $value; ?>" 
                        <?php echo $value == $form->get('transport')->getValue() ? 'checked' : ''; ?>
                    />
                </dt>
                <dd>
                    <h5>
                        <?php echo $label; ?>
                    </h5>
                </dd>
                <?php endforeach; ?>
                <dt>
                </dt>
                <dd>
                    <button class="" type="submit">Continue &rightarrow;</button>
                </dd>
            </dl>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>