<?php

?>
<div class="container">
    <?php
        echo $this->flashMessenger()->render('error', array('alert alert-error unstyled'));
        echo $this->flashMessenger()->render('success', array('alert alert-success unstyled'));
        echo $this->flashMessenger()->render('info', array('alert alert-info unstyled'));
    ?>
    <div class="row">
        <div class="span12">
            <legend>
                <h3>Email Transport Settings</h3>
            </legend>
            <h5>
                Select preferred transport
            </h5>
            <?php echo $this->form()->openTag($form); ?>
            <dl class="dl-horizontal">
                <?php foreach($form->get('transport')->getValueOptions() as $value => $label): ?>
                <dt>
                    <input 
                        type="radio" 
                        name="transport" 
                        value="<?php echo $value; ?>" 
                        <?php echo $value == $form->get('transport')->getValue() ? 'checked' : ''; ?>
                    />
                    <?php
                        
                    ?>
                </dt>
                <dd>
                   <strong><?=$label;?></strong>
                </dd>
                <?php endforeach; ?>
                <dt>
                    &nbsp;
                </dt>
                <dd>
                    &nbsp;
                </dd>
                <dt>
                &nbsp;
                </dt>
                <dd>
                    <button class="" type="submit">Continue &rightarrow;</button>
                </dd>
            </dl>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>