<div class="container">
    <?php
        echo $this->flashMessenger()->render('error', array('alert alert-error unstyled'));
        echo $this->flashMessenger()->render('success', array('alert alert-success unstyled'));
        echo $this->flashMessenger()->render('info', array('alert alert-info unstyled'));
    ?>
    <div class="row">
        <div class="span12">
            <legend>
                <h3><?php echo $option->getName(); ?> Settings</h3>
            </legend>
            <?php echo $this->form()->openTag($option->getForm()); ?>
            <dl>
                <?php foreach($option->getForm() as $element): ?>
                <dt>
                    <?php if(!$element instanceof \Zend\Form\Element\Button && $element->getLabel()): ?>
                        <?php echo $this->formLabel($element); ?>
                    <?php endif; ?>
                </dt>
                <dd>
                    <?php
                        echo $this->formElement($element);
                    ?>
                </dd>
                <?php endforeach; ?>
                <dt>
                    &nbsp;
                </dt>
                <dd>
                    <button type="submit" name="action" value="save"><strong>Save</strong></button>
                </dd>
                <dt>
                    &nbsp;
                </dt>
                <dd>
                    <input type="email" name="send_test_to" placeholder="Email address." />
                    <button type="submit" name="action" value="test">Send Test Email</button>
                </dd>
            </dl>
            
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>